@startuml
participant Client
participant Singleton
participant SingletonInstance

Client -> Singleton: getInstance()

opt instance == null
  Singleton -> SingletonInstance: <<create>>
  SingletonInstance++
end

Client <-- Singleton: instance
@enduml