@startuml
[*] --> 대출_가능
대출_가능 --> 대출_중 : 체크아웃
대출_중 --> 예약_중 : 예약
예약_중 --> 보관_중 : 반환
보관_중 --> 대출_가능 : 예약_취소
보관_중 --> 대출_가능 : 보관_종료
대출_중 --> 대출_가능 : 반환
예약_중 --> 대출_중 : 예약_취소
@enduml

@startuml
class Book {
    -state State

    +체크아웃(): void
    +예약(): void
    +예약_취소(): void
    +반환(): void
    +보관_종료(): void
    +setState(State state): void
}

interface State {
    +체크아웃(Book book): void
    +예약(Book book): void
    +예약_취소(Book book): void
    +반환(Book book): void
    +보관_종료(Book book): void
}

class 대출_가능 {
    +체크아웃(Book book): void
    +예약(Book book): void
    +예약_취소(Book book): void
    +반환(Book book): void
    +보관_종료(Book book): void
}
class 대출_중 {
    +체크아웃(Book book): void
    +예약(Book book): void
    +예약_취소(Book book): void
    +반환(Book book): void
    +보관_종료(Book book): void
}
class 보관_중 {
    +체크아웃(Book book): void
    +예약(Book book): void
    +예약_취소(Book book): void
    +반환(Book book): void
    +보관_종료(Book book): void
}
class 예약_중 {
    +체크아웃(Book book): void
    +예약(Book book): void
    +예약_취소(Book book): void
    +반환(Book book): void
    +보관_종료(Book book): void
}

Book o--> State
State <|.. 대출_가능
State <|.. 대출_중
State <|.. 보관_중
State <|.. 예약_중
@enduml